### ISSUE TITLE
setup.py develop fails on m1 mac

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-python-bindings#125]
here's the error I get

```
running develop
running egg_info
creating igl.egg-info
writing igl.egg-info/PKG-INFO
writing dependency_links to igl.egg-info/dependency_links.txt
writing requirements to igl.egg-info/requires.txt
writing top-level names to igl.egg-info/top_level.txt
writing manifest file 'igl.egg-info/SOURCES.txt'
reading manifest file 'igl.egg-info/SOURCES.txt'
writing manifest file 'igl.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    setup(
  File "/Users/alecjacobson/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/alecjacobson/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/alecjacobson/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/alecjacobson/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/alecjacobson/miniconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/Users/alecjacobson/miniconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/Users/alecjacobson/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/alecjacobson/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.build_extension(ext)
  File "setup.py", line 57, in build_extension
    if "arm64-apple" in tmp:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by teseoch** [comment]
i just merged a PR that should fix it

**Comment by alecjacobson** [comment]
Which PR? I side-stepped this issue in https://github.com/libigl/libigl-python-bindings/pull/130 by changing the line to 
```python
if tmp and ...
```

**Comment by teseoch** [comment]
https://github.com/libigl/libigl-python-bindings/commit/8bb266c7147e9f1ff3a38330af1a806fe02b52c5

this one, reads env vars with default

**Comment by alecjacobson** [comment]
excellent!
