### ISSUE TITLE
`python setup.py develop` fails

### ISSUE THREAD

**Issue by Kobe972** [libigl/libigl-python-bindings#133]
```
E:\编程\python\libigl-python-bindings>python setup.py develop
running develop
D:\Program Files (x86)\python\lib\site-packages\setuptools\command\easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
D:\Program Files (x86)\python\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing igl.egg-info\PKG-INFO
writing dependency_links to igl.egg-info\dependency_links.txt
writing requirements to igl.egg-info\requires.txt
writing top-level names to igl.egg-info\top_level.txt
reading manifest file 'igl.egg-info\SOURCES.txt'
writing manifest file 'igl.egg-info\SOURCES.txt'
running build_ext
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMake Deprecation Warning at cmake/Warnings.cmake:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)


用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.7.0+b89cb5fde
版权所有(C) Microsoft Corporation。保留所有权利。

  Checking Build System
  Performing download step (git clone) for 'libigl-populate'
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': OpenSSL SSL_read: Connection was reset, errno 10054
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': OpenSSL SSL_read: Connection was reset, errno 10054
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': Failed to connect to github.com port 443: Timed out
  -- Had to git clone more than once: 3 times.
  CMake Error at libigl-subbuild/libigl-populate-prefix/tmp/libigl-populate-gitclone.cmake:39 (message):
    Failed to clone repository: 'https://github.com/libigl/libigl.git'


D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(234,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [E:\编程\python\libigl-python-bindings\build\temp.win-amd64-3.6\Release\_deps\libigl-subbuild\libigl-populate.vcxproj]

CMake Error at D:/Program Files/CMake/share/cmake-3.23/Modules/FetchContent.cmake:1088 (message):
  Build step for libigl failed: 1
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.23/Modules/FetchContent.cmake:1217:EVAL:2 (__FetchContent_directPopulate)
  D:/Program Files/CMake/share/cmake-3.23/Modules/FetchContent.cmake:1217 (cmake_language)
  D:/Program Files/CMake/share/cmake-3.23/Modules/FetchContent.cmake:1260 (FetchContent_Populate)
  cmake/PyiglDependencies.cmake:25 (FetchContent_MakeAvailable)
  CMakeLists.txt:20 (include)


-- Configuring incomplete, errors occurred!
See also "E:/编程/python/libigl-python-bindings/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 135, in <module>
    test_suite="tests"
  File "D:\Program Files (x86)\python\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Program Files (x86)\python\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Program Files (x86)\python\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Program Files (x86)\python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Program Files (x86)\python\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "D:\Program Files (x86)\python\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "D:\Program Files (x86)\python\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Program Files (x86)\python\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 32, in run
    self.build_extension(ext)
  File "setup.py", line 108, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "D:\Program Files (x86)\python\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'E:\\编程\\python\\libigl-python-bindings', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\\编程\\python\\libigl-python-bindings\\igl', '-DPYTHON_EXECUTABLE=D:\\Program Files (x86)\\python\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=E:\\编程\\python\\libigl-python-bindings\\igl', '-A', 'x64']' returned non-zero exit status 1.
```

**Comment by nodtem66** [comment]
I guess the main problem was not being able to clone the `libigl` from Github.
```
  Checking Build System
  Performing download step (git clone) for 'libigl-populate'
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': OpenSSL SSL_read: Connection was reset, errno 10054
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': OpenSSL SSL_read: Connection was reset, errno 10054
  Cloning into 'libigl-src'...
  fatal: unable to access 'https://github.com/libigl/libigl.git/': Failed to connect to github.com port 443: Timed out
  -- Had to git clone more than once: 3 times.
  CMake Error at libigl-subbuild/libigl-populate-prefix/tmp/libigl-populate-gitclone.cmake:39 (message):
    Failed to clone repository: 'https://github.com/libigl/libigl.git'
```
To investigate the problem, I have a few questions.
Can you clone `https://github.com/libigl/libigl.git` with the command line, i.e. `git clone https://github.com/libigl/libigl.git'`?

**Comment by Kobe972** [comment]
Thanks. China has partially banned github. I'll install binary package instead.

**Comment by alecjacobson** [comment]
closing due to age, please reopen if still an issue.
