### ISSUE TITLE
OpenGL.GL.shaders.ShaderValidationError: Validation failure (0)

### ISSUE THREAD

**Issue by Kobe972** [libigl/libigl-python-bindings#134]
I ran basic_display.py，and it fails.
```
Traceback (most recent call last):
  File "e:\programming\python\pyigl_viewer\PyIGL_viewer\viewer\viewer_widget.py", line 85, in initializeGL
    self.add_shaders()
  File "e:\programming\python\pyigl_viewer\PyIGL_viewer\viewer\viewer_widget.py", line 74, in add_shaders
    self.shaders[shader_name] = ShaderProgram(shader_name, os.path.join(dir_name, f),
  File "e:\programming\python\pyigl_viewer\PyIGL_viewer\viewer\shader.py", line 16, in __init__
    self.program = shaders.compileProgram(vertex_shader, fragment_shader)
  File "D:\ProgramData\Miniconda3\lib\site-packages\OpenGL\GL\shaders.py", line 211, in compileProgram
    program.check_validate()
  File "D:\ProgramData\Miniconda3\lib\site-packages\OpenGL\GL\shaders.py", line 109, in check_validate
    raise ShaderValidationError(
OpenGL.GL.shaders.ShaderValidationError: Validation failure (0)
```

**Comment by SEU-PZH** [comment]
how to fix it?
