### ISSUE TITLE
Getting an error trying to build python

### ISSUE THREAD

**Issue by dbiswas2808** [libigl/libigl-python-bindings#228]
I'm on M1 macOS Monterey.
With:
`sudo python setup.py build --debug develop `
```
[ 96%] Built target mpfr
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/libigl-python-bindings/setup.py", line 144, in <module>
    setup(
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
    return run_commands(dist)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
    dist.run_commands()
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
    super().run()
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
    self.run_command(cmd_name)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/libigl-python-bindings/setup.py", line 34, in run
    self.build_extension(ext)
  File "/Users/deepanjanbiswas/Documents/GitHub/libigl/libigl-python-bindings/setup.py", line 124, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Debug', '--', '-j8']' returned non-zero exit status 2.
```

**Comment by alecjacobson** [comment]
Please try the newest version v2.5.4.dev0 as a lot has changed.
